name: Deploy to Render and GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "deploys"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: deploy
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './HTML_CSS_JavaScript_Figma/page/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
